name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  table_calendar: ^3.2.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  fl_chart: ^0.70.2
  audioplayers: ^5.2.1
  shared_preferences: ^2.0.15
  image_picker: ^1.0.7
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  provider: ^6.0.0
  lottie: ^3.3.1
  animations: ^2.0.7
  file_picker: ^10.0.0
  share_plus: ^10.1.4
  open_file: ^3.3.2
  # flutter_local_notifications: ^16.1.0
  # workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/announcement-sound-effect-254037.mp3
    - assets/images/background1.jpg
    - assets/sounds/notification-sound-2-253324.mp3
    - assets/loadingScence.json
    - assets/data/notes.json
    - assets/data/users.json
    - assets/data/tasks.json

